'use strict';

const byId=(id)=>document.getElementById(id);
const clone=(value)=>JSON.parse(JSON.stringify(value));
const state={contractTemplate:null,contract:null,approvedContract:null,nearMiles:null,qualityFloor:'4_star',adapter:'ap2',eventPaths:null,lastEvents:null,lastReceipt:null,receiptCache:new Map(),bench:null,benchManifest:null};
const candidates=[
  {id:'pendry',name:'The Pendry',merchant:'merchant_pendry_hy',total:389,distance:.7,refundable:true,quality:4.5,memberValue:50,valueLabel:'Illustrative hotel benefit',effective:339},
  {id:'equinox',name:'Equinox Hotel',merchant:'merchant_equinox_hy',total:360,distance:.2,refundable:true,quality:4.5,memberValue:0,valueLabel:'No eligible value',effective:360},
  {id:'mercer',name:'The Mercer',merchant:'merchant_mercer',total:404,distance:1.8,refundable:false,quality:5,memberValue:0,valueLabel:'Hidden $45 fee',effective:404}
];
const fallbackTemplate={schema_id:'oa://contracts/hotel-booking/1.2.0',contract_id:'oa_demo_hy_2048',version:'1.2.0',status:'draft',assurance_level:'decision_sensitive',approved_fields:{domain:'travel.hotel',check_in:'2026-09-24',constraints:{refundable_until_local:'18:00',final_total_usd_max:400,distance_from_landmark_miles_max:null},preferences:{quality_floor:'4_star',quality_over_lowest_price:true},value_policy:{objective:'minimize_effective_cost',include_only_deterministically_eligible_value:true}},clarification_policy:{method:'expected_decision_regret',question_cost_usd:5,ask_when:'expected_regret_gt_question_cost'},evidence_policy:{required_claims:['merchant_identity','final_amount','refundability','distance','benefit_eligibility'],allowed_states:['verified','pending','inferred','unobservable','mismatch'],retention_days:395},observability:{merchant_identity:'required',final_amount:'required',refundability:'required',distance:'eventual',benefit_eligibility:'eventual'},protocol_bindings:[{protocol:'ap2',adapter_version:'0.2.0-demo'},{protocol:'ucp',adapter_version:'2026-01-11-demo'},{protocol:'acp',adapter_version:'2026-09-demo'}],provenance:{hash_algorithm:'sha256',contract_hash:'',compiler_version:'outcome-compiler/2.0.0',policy_bundle_version:'assurance-policy/1.1.0',model_id:'language-parser-04',prompt_hash:'sha256:49ce8ad2'}};

function toast(message){const node=byId('toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),1800)}
async function digest(value){const input=typeof value==='string'?value:JSON.stringify(value);if(crypto?.subtle){const bytes=new TextEncoder().encode(input);const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('')}let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h>>>0).toString(16).padStart(8,'0').repeat(8)}
function deepFreeze(object){Object.freeze(object);Object.values(object).forEach(value=>{if(value&&typeof value==='object'&&!Object.isFrozen(value))deepFreeze(value)});return object}
function setJourney(step){const order=['compile','clarify','optimize','approve','observe','verify'];const current=order.indexOf(step);document.querySelectorAll('.journey-step').forEach((button,index)=>{button.classList.toggle('active',index===current);button.classList.toggle('complete',index<current)})}
function currentLimit(){return state.nearMiles??.5}
function rankCandidates(){const limit=currentLimit();return candidates.map(candidate=>({...candidate,passes:candidate.refundable&&candidate.total<=400&&candidate.distance<=limit&&candidate.quality>=4})).sort((a,b)=>{if(a.passes!==b.passes)return a.passes?-1:1;return a.effective-b.effective})}
function winner(){return rankCandidates().find(candidate=>candidate.passes)}
async function syncContractHash(){if(!state.contract)return;const hashInput=clone(state.contract);delete hashInput.provenance.contract_hash;const hash=await digest(hashInput);state.contract.provenance.contract_hash=`sha256:${hash}`;byId('shortHash').textContent=`${hash.slice(0,12)}…${hash.slice(-8)}`}

function renderContractRows(){const distance=state.nearMiles?`≤ ${state.nearMiles} mile${state.nearMiles===1?'':'s'}`:'Requires one answer';const rows=[
  ['MUST','Refundable until 6 PM','approved'],['MUST','Final total ≤ $400','approved'],['DISTANCE',distance,state.nearMiles?'approved':'unresolved'],['PREFER','4-star+ quality; quality over lowest sticker price','approved'],['VALUE','Minimize effective cost using deterministically eligible value','approved'],['EVIDENCE','Merchant · amount · terms · distance · benefit','required']
];
  byId('contractRows').innerHTML=rows.map(([type,value,status])=>`<div class="contract-row"><span>${type}</span><b>${value}</b><i class="${status}">${status}</i></div>`).join('');
  byId('viewJson').disabled=false;byId('approveContract').disabled=!state.nearMiles;
}
function renderClarification(){setJourney('clarify');byId('stagePanel').innerHTML=`<article class="stage-card full"><p class="eyebrow">DECISION-REGRET TEST</p><h3>Ask only when an answer can change the action.</h3><p>The same uncertainty can be harmless or consequential. Regretware tests the candidate ranking under each plausible answer before it interrupts the Member.</p><div class="regret-grid"><div class="ambiguity"><div class="ambiguity-top"><span>IGNORE</span><b>$0 EXPECTED REGRET</b></div><h4>What does “really nice” mean?</h4><small>Changing the quality floor from 4-star to 4.5-star does not change the winner. No question earned.</small><div class="regret-bar"><i style="width:0"></i></div></div><div class="ambiguity ask"><div class="ambiguity-top"><span>ASK</span><b>$13.02 EXPECTED REGRET</b></div><h4>What does “near” mean?</h4><small>A 0.5-mile limit selects Equinox. A 1-mile limit selects The Pendry after verified Member value. The winner flips.</small><div class="regret-bar"><i style="width:74%"></i></div></div></div><div class="question-box"><p>“When you say near, is within one mile okay?”</p><div><button data-near="0.5">No, 0.5 mi</button><button data-near="1">Yes, 1 mi</button></div></div></article>`;document.querySelectorAll('[data-near]').forEach(button=>button.addEventListener('click',()=>answerDistance(Number(button.dataset.near))))}
async function answerDistance(value){state.nearMiles=value;state.contract.approved_fields.constraints.distance_from_landmark_miles_max=value;await syncContractHash();renderContractRows();renderOptimize();toast(value===1?'One-mile answer changes the winner':'Half-mile answer keeps the closest hotel')}
function renderOptimize(){setJourney('optimize');const ranked=rankCandidates();const selected=ranked.find(candidate=>candidate.passes);const next=ranked.filter(candidate=>candidate.passes)[1];const delta=next?next.effective-selected.effective:0;byId('stagePanel').innerHTML=`<article class="stage-card full"><p class="eyebrow">DETERMINISTIC MEMBERSHIP VALUE ROUTER</p><h3>Rules reject. Eligibility routes. Effective value decides.</h3><p>All money, dates, distance, refundability and benefit eligibility are evaluated in code. The language model is not in this path.</p><div class="candidate-grid">${ranked.map((candidate,index)=>`<div class="candidate ${candidate.id===selected.id?'winner':''} ${candidate.passes?'':'failed'}">${candidate.id===selected.id?'<i class="winner-flag">WINNER</i>':''}<span>${String(index+1).padStart(2,'0')} · ${candidate.passes?'COMPLIANT':'REJECTED'}</span><h4>${candidate.name}</h4><dl><dt>Final total</dt><dd>$${candidate.total}</dd><dt>Distance</dt><dd>${candidate.distance} mi</dd><dt>Refundable</dt><dd>${candidate.refundable?'Yes':'No'}</dd><dt>Member value</dt><dd>$${candidate.memberValue}</dd></dl><strong>$${candidate.effective} <small>EFFECTIVE</small></strong></div>`).join('')}</div><div class="delta-box"><b>VERIFIED VALUE DELTA · +$${delta}</b> versus the next-best compliant outcome. The winner is transparent, and the counterfactual is preserved in the decision record.</div></article>`}
function renderApproval(){setJourney('approve');const selected=winner();byId('stagePanel').innerHTML=`<article class="stage-card dark"><p class="eyebrow">IMMUTABLE DECISION RECORD</p><h3>${selected.name} · $${selected.total}</h3><p>Selected under contract ${state.contract.version}. Effective cost $${selected.effective}; verified value delta +$${rankCandidates().filter(x=>x.passes)[1].effective-selected.effective}.</p></article><article class="stage-card"><p class="eyebrow">SEPARATE AUTHORITY</p><h3>Contract frozen. Agent write access removed.</h3><p>The purchasing agent receives a hash-bound read-only copy. Only a new version, approved by the trusted surface, may change approved fields.</p></article>`}
function renderStage(step){if(!state.contract&&step!=='compile'){toast('Compile the outcome contract first');return}if(step==='compile'){setJourney('compile');byId('stagePanel').innerHTML='';return}if(step==='clarify')renderClarification();if(step==='optimize')renderOptimize();if(step==='approve')state.approvedContract?renderApproval():toast('Answer the decision-sensitive question, then approve');if(step==='observe'||step==='verify'){document.querySelector('#verifier').scrollIntoView({behavior:'smooth'});setJourney(step)}}

async function compileContract(){state.contract=clone(state.contractTemplate||fallbackTemplate);state.contract.status='draft';state.approvedContract=null;state.nearMiles=null;byId('contractStatus').textContent='DRAFT';byId('contractStatus').className='status pending';byId('approveContract').textContent='Approve + freeze';renderContractRows();await syncContractHash();renderClarification();toast('Portable outcome contract compiled')}
async function approveContract(){if(!state.contract)return;if(!state.nearMiles){toast('One ambiguity can change the winner—answer it first');renderClarification();return}const selected=winner();state.contract.status='approved';state.contract.approved_at='2026-09-23T15:10:00Z';state.contract.decision={selected_candidate_id:selected.id,selected_merchant_id:selected.merchant,approved_total_usd:selected.total,expected_member_value_usd:selected.memberValue,effective_cost_usd:selected.effective,next_best_value_delta_usd:rankCandidates().filter(x=>x.passes)[1].effective-selected.effective};await syncContractHash();state.approvedContract=deepFreeze(clone(state.contract));byId('contractStatus').textContent='APPROVED';byId('contractStatus').className='status approved';byId('approveContract').textContent='Approved + immutable';byId('approveContract').disabled=true;renderApproval();toast('Contract frozen and hash-bound')}

function normalizedEvents(adapter,failure){const base=state.eventPaths?.paths?.[adapter]||['intent.compiled','contract.approved','checkout.proposed','payment.authorized','order.confirmed','settlement.posted','benefit.observed'].map((event_name,index)=>({sequence:index+1,event_name,source:event_name.split('.')[0],source_type:'normalized'}));const selected=state.approvedContract.decision;const selectedCandidate=candidates.find(candidate=>candidate.id===selected.selected_candidate_id);return base.map(event=>{const item=clone(event);item.timestamp=`2026-09-23T15:${String(10+event.sequence).padStart(2,'0')}:00Z`;item.trace_id=state.eventPaths?.trace_id||'2f1c9e8aa8e94e03b4c10d9482f4d032';if(item.event_name==='intent.compiled')item.body={contract_hash:state.approvedContract.provenance.contract_hash};if(item.event_name==='contract.approved')item.body={contract_id:state.approvedContract.contract_id,version:state.approvedContract.version};if(item.event_name==='checkout.proposed')item.body={merchant_id:selected.selected_merchant_id,total_usd:selected.approved_total_usd,distance_miles:selectedCandidate.distance};if(item.event_name==='payment.authorized')item.body={authorized_usd:selected.approved_total_usd,status:'authorized'};if(item.event_name==='order.confirmed')item.body={merchant_id:selected.selected_merchant_id,refundable:true,cancel_by_local:'18:00'};if(item.event_name==='settlement.posted')item.body={settled_usd:selected.approved_total_usd};if(item.event_name==='benefit.observed')item.body={eligible_value_usd:selected.expected_member_value_usd,state:'verified'};return item}).map(item=>{if(failure==='hidden_fee'&&item.event_name==='settlement.posted')item.body.settled_usd+=45;if(failure==='nonrefundable_swap'&&item.event_name==='order.confirmed')item.body.refundable=false;if(failure==='missing_amount'&&item.event_name==='settlement.posted')item.body={state:'missing'};if(failure==='pending_benefit'&&item.event_name==='benefit.observed')item.body.state='pending';return item}).concat(failure==='agent_overwrite'?[{sequence:8,event_name:'agent.contract.overwrite_attempt',source:'purchasing_agent',source_type:'agent',timestamp:'2026-09-23T15:18:00Z',trace_id:state.eventPaths?.trace_id,body:{path:'approved_fields.constraints.final_total_usd_max',attempted_value:500,result:'blocked'}}]:[])}
function evidenceClaim(label,stateName,detail){return{label,state:stateName,detail}}
async function evaluateEvents(events){const approved=state.approvedContract;const order=events.find(x=>x.event_name==='order.confirmed');const checkout=events.find(x=>x.event_name==='checkout.proposed');const settlement=events.find(x=>x.event_name==='settlement.posted');const benefit=events.find(x=>x.event_name==='benefit.observed');const overwrite=events.find(x=>x.event_name==='agent.contract.overwrite_attempt');const claims=[];
  claims.push(evidenceClaim('Contract integrity','verified',overwrite?'Overwrite blocked; approved hash unchanged':'Approved SHA-256 matches verifier copy'));
  claims.push(evidenceClaim('Merchant identity',order?.body?.merchant_id===approved.decision.selected_merchant_id?'verified':'mismatch',order?.body?.merchant_id||'No merchant event'));
  const amount=settlement?.body?.settled_usd;claims.push(evidenceClaim('Final settled amount',typeof amount!=='number'?'unobservable':amount===approved.decision.approved_total_usd?'verified':'mismatch',typeof amount==='number'?`$${amount} observed · $${approved.decision.approved_total_usd} approved`:'Settlement amount absent'));
  claims.push(evidenceClaim('Refundability',order?.body?.refundable===true?'verified':order?'mismatch':'unobservable',order?.body?.refundable===true?'Refundable until 6 PM':order?'Terms changed after approval':'No order evidence'));
  claims.push(evidenceClaim('Distance',checkout?.body?.distance_miles<=state.nearMiles?'verified':'mismatch',checkout?.body?.distance_miles!=null?`${checkout.body.distance_miles} mi · limit ${state.nearMiles} mi`:'No distance evidence'));
  claims.push(evidenceClaim('Membership value',benefit?.body?.state==='pending'?'pending':benefit?.body?.eligible_value_usd===approved.decision.expected_member_value_usd?'verified':benefit?'mismatch':'unobservable',benefit?.body?.state==='pending'?'Eligible value awaits posting':benefit?`$${benefit.body.eligible_value_usd} observed`:'No benefit event'));
  const orderOf=['mismatch','unobservable','pending','inferred','verified'];const overall=orderOf.find(status=>claims.some(claim=>claim.state===status))||'verified';const eventHash=await digest(events);const key=`${approved.provenance.contract_hash}:${eventHash}`;if(state.receiptCache.has(key))return{...state.receiptCache.get(key),cacheHit:true};const receiptHash=await digest(key);const receipt={id:`oa_rcpt_${receiptHash.slice(0,12)}`,status:overall,claims,eventHash:`sha256:${eventHash}`,contractHash:approved.provenance.contract_hash,cacheHit:false,verifiedAt:'2026-09-23T15:19:00Z'};state.receiptCache.set(key,receipt);return receipt}
function renderEvents(events){byId('eventStream').innerHTML=`<div class="event-list">${events.map(item=>`<div class="event"><em>${String(item.sequence).padStart(2,'0')}</em><b>${item.event_name}</b><span>${item.source} · ${item.source_type}</span></div>`).join('')}</div>`}
function renderReceipt(receipt){state.lastReceipt=receipt;const titles={verified:'Outcome verified',mismatch:'Outcome mismatch',pending:'Verification pending',unobservable:'Outcome unobservable',inferred:'Outcome inferred'};byId('receiptVerdict').textContent=titles[receipt.status];byId('receiptState').textContent=receipt.status.toUpperCase();byId('receiptState').className=`receipt-state ${receipt.status}`;byId('receiptId').textContent=receipt.id;byId('idempotencyState').textContent=receipt.cacheHit?'cache hit · no duplicate action':'new result stored';byId('claimList').innerHTML=receipt.claims.map(claim=>`<div class="claim"><b>${claim.label}</b><small>${claim.detail}</small><span class="${claim.state}">${claim.state.toUpperCase()}</span></div>`).join('');byId('rerunVerifier').disabled=false;byId('openRecovery').disabled=false}
async function runVerifier(reuse=false){if(!state.approvedContract){toast('Approve and freeze the contract before verification');document.querySelector('#contract').scrollIntoView({behavior:'smooth'});return}const failure=byId('failureMode').value;const events=reuse&&state.lastEvents?state.lastEvents:normalizedEvents(state.adapter,failure);state.lastEvents=events;renderEvents(events);const receipt=await evaluateEvents(events);renderReceipt(receipt);setJourney('verify');toast(receipt.cacheHit?'Idempotent re-run returned the same receipt':`Verifier issued ${receipt.status} receipt`)}
function openRecovery(){const receipt=state.lastReceipt;if(!receipt)return;const items=[['01','Approved contract + SHA-256',receipt.contractHash.slice(0,22)+'…'],['02','Normalized event log',receipt.eventHash.slice(0,22)+'…'],['03','Independent receipt',receipt.id],['04','Claim-level evidence states',`${receipt.claims.length} claims`],['05','Decision counterfactual',`+$${state.approvedContract.decision.next_best_value_delta_usd} value delta`]];byId('recoveryItems').innerHTML=items.map(([index,label,value])=>`<div class="recovery-item"><span>${index}</span><b>${label}<small style="display:block;color:#7a8a99;font-weight:400">${value}</small></b><i>READY</i></div>`).join('');byId('recoverySummary').innerHTML=receipt.status==='mismatch'?'<b>Recommended handoff:</b> servicing receives the original request, approved fields, selected counterfactual, event provenance, and the exact mismatched claim. No autonomous refund or dispute action is taken.':'<b>Evidence package complete:</b> this receipt can be retained for later servicing without asking the Member to reconstruct the journey.';byId('recoveryDrawer').classList.add('open');byId('recoveryDrawer').setAttribute('aria-hidden','false')}

function classifyAssurance(item){if(item.failure==='merchant_alias')return'verified';if(item.evidence==='missing_amount'||item.evidence==='missing_refundability')return'unobservable';if(item.evidence==='pending_benefit')return'pending';if(item.evidence==='inferred_merchant')return'inferred';if(['duplicate_event','out_of_order','none'].includes(item.failure))return'verified';return'mismatch'}
function classifyBaseline(item){if(['nonrefundable_swap','price_change','quantity_change'].includes(item.failure))return'mismatch';return'verified'}
function metricsFor(cases,classifier,kind){const results=cases.map(item=>({item,predicted:classifier(item),asked:kind==='oa'?item.question_needed:(item.scenario.includes('ambiguity')||item.evidence!=='complete')}));const correct=results.filter(row=>row.predicted===row.item.expected_verdict).length;const violations=results.filter(row=>row.item.expected_verdict==='mismatch');const detected=violations.filter(row=>row.predicted==='mismatch').length;const questionCases=results.filter(row=>row.item.question_needed);const missedQuestions=questionCases.filter(row=>!row.asked).length;const value=results.filter(row=>row.predicted===row.item.expected_verdict&&!['mismatch','unobservable'].includes(row.item.expected_verdict)).reduce((sum,row)=>sum+row.item.verified_value_delta_usd,0);const complete=results.filter(row=>row.item.evidence==='complete').length;const holdout=results.filter(row=>row.item.split==='blind_holdout');return{n:cases.length,classification:correct/cases.length,violation:violations.length?detected/violations.length:1,questions:results.filter(row=>row.asked).length/cases.length,value,evidence:complete/cases.length,regret:questionCases.length?missedQuestions/questionCases.length:0,holdout:holdout.filter(row=>row.predicted===row.item.expected_verdict).length/holdout.length}}
function wilson(p,n){if(!n)return 0;const z=1.96;return z*Math.sqrt((p*(1-p)+z*z/(4*n))/n)/(1+z*z/n)}
async function runBench(){const cases=state.bench?.cases||[];if(!cases.length){toast('Benchmark fixtures unavailable');return}byId('benchPulse').className='running';byId('benchStatus').textContent='Running one code path across 24 cases…';byId('runBench').disabled=true;await new Promise(resolve=>setTimeout(resolve,550));const oa=metricsFor(cases,classifyAssurance,'oa');const baseline=metricsFor(cases,classifyBaseline,'baseline');const values=[`${(oa.classification*100).toFixed(1)}%`,`${(oa.violation*100).toFixed(1)}%`,oa.questions.toFixed(2),`$${oa.value}`,`${(oa.evidence*100).toFixed(1)}%`,`${(oa.regret*100).toFixed(1)}%`];document.querySelectorAll('#metricGrid strong').forEach((node,index)=>node.textContent=values[index]);byId('oaScore').textContent=`${(oa.classification*100).toFixed(1)}% ± ${(wilson(oa.classification,oa.n)*100).toFixed(1)}`;byId('baselineScore').textContent=`${(baseline.classification*100).toFixed(1)}% ± ${(wilson(baseline.classification,baseline.n)*100).toFixed(1)}`;byId('oaHoldout').textContent=`${(oa.holdout*100).toFixed(1)}%`;byId('baselineHoldout').textContent=`${(baseline.holdout*100).toFixed(1)}%`;byId('benchPulse').className='complete';byId('benchStatus').textContent='Reproducible synthetic run complete';byId('runBench').disabled=false;toast('OutcomeBench completed from frozen fixtures')}

async function loadArtifacts(){const requests=[['contractTemplate','./data/hotel-contract-template.json'],['eventPaths','./data/normalized-event-paths.json'],['bench','./bench/gold-set-v2.json'],['benchManifest','./bench/manifest-v2.json']];await Promise.all(requests.map(async([key,url])=>{try{const response=await fetch(url);if(!response.ok)throw new Error(response.status);state[key]=await response.json()}catch(error){console.warn(`Artifact unavailable: ${url}`,error)}}));state.contractTemplate=state.contractTemplate||fallbackTemplate;if(state.bench){const hash=await digest(state.bench);byId('benchHash').textContent=`sha256:${hash.slice(0,12)}…${hash.slice(-8)}`}}

byId('compileButton').addEventListener('click',compileContract);
byId('viewJson').addEventListener('click',()=>{if(!state.contract)return;byId('jsonCode').textContent=JSON.stringify(state.contract,null,2);byId('jsonModal').hidden=false});
byId('approveContract').addEventListener('click',approveContract);
byId('closeJson').addEventListener('click',()=>byId('jsonModal').hidden=true);
byId('jsonModal').addEventListener('click',(event)=>{if(event.target===byId('jsonModal'))byId('jsonModal').hidden=true});
byId('copyJson').addEventListener('click',async()=>{await navigator.clipboard.writeText(JSON.stringify(state.contract,null,2));toast('Contract JSON copied')});
byId('downloadJson').addEventListener('click',()=>{const link=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(state.contract,null,2)],{type:'application/json'}));link.href=url;link.download=`${state.contract.contract_id}-${state.contract.version}.json`;link.click();URL.revokeObjectURL(url)});
document.querySelectorAll('.journey-step').forEach(button=>button.addEventListener('click',()=>renderStage(button.dataset.step)));
document.querySelectorAll('.tier-list button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.tier-list button').forEach(node=>node.classList.remove('selected'));button.classList.add('selected');toast(`${button.querySelector('span').textContent} assurance policy selected`)}));
document.querySelectorAll('#adapterButtons button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('#adapterButtons button').forEach(node=>node.classList.remove('active'));button.classList.add('active');state.adapter=button.dataset.adapter;state.lastEvents=null;toast(`${state.adapter.toUpperCase()} adapter selected`)}));
byId('runVerifier').addEventListener('click',()=>runVerifier(false));byId('rerunVerifier').addEventListener('click',()=>runVerifier(true));byId('openRecovery').addEventListener('click',openRecovery);byId('closeRecovery').addEventListener('click',()=>{byId('recoveryDrawer').classList.remove('open');byId('recoveryDrawer').setAttribute('aria-hidden','true')});byId('runBench').addEventListener('click',runBench);
document.addEventListener('keydown',(event)=>{if(event.key==='Escape'){byId('jsonModal').hidden=true;byId('recoveryDrawer').classList.remove('open')}});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll('.topbar nav a').forEach(link=>link.classList.toggle('active',link.getAttribute('href')===`#${entry.target.id}`))}}),{rootMargin:'-35% 0px -55%'});['lab','contract','verifier','bench','boundary'].forEach(id=>{const node=byId(id);if(node)observer.observe(node)});
loadArtifacts();
